# Development Docker Compose - Hot Reload for UI
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.dev
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
